### ISSUE TITLE
Error When running website locally

### ISSUE THREAD

**Issue by Wholloran** [openforge/OPENFORGE.IO#133]
When running the website in develope the following error is being displayed in the terminal. I'm not sure if this is an issue with my machine or the way I am serving it but posting it to be safe.

`[ ERROR ]  runtime console.error: /
           Error: Could not parse CSS stylesheet at exports.evaluateStylesheet
           (/Users/billy/OPENFORGE.IO/node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:18:21)
           at HTMLStyleElementImpl._attach
           (/Users/billy/OPENFORGE.IO/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:23:5)
           at HTMLHeadElementImpl.insertBefore
           (/Users/billy/OPENFORGE.IO/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:230:22)
           at HTMLHeadElement.insertBefore
           (/Users/billy/OPENFORGE.IO/node_modules/jsdom/lib/jsdom/living/generated/Node.js:182:45)
           at insertStyles
           (/Users/billy/OPENFORGE.IO/node_modules/@stencil/core/dist/server/index.js:4963:18)
           at inlineComponentStyles
           (/Users/billy/OPENFORGE.IO/node_modules/@stencil/core/dist/server/index.js:4956:5)
           at
           /Users/billy/OPENFORGE.IO/node_modules/@stencil/core/dist/server/index.js:5443:17
           at Generator.next (<anonymous>) at
           /Users/billy/OPENFORGE.IO/node_modules/@stencil/core/dist/server/index.js:5419:71
           at new Promise (<anonymous>),
           footer{background:#282828;color:#fff;padding:5rem 0 2rem}footer
           h2{color:#e88212;font-size:1.6rem;margin-bottom:2rem}footer a,footer
           p{color:#fff;display:block;font-size:.8em;margin-bottom:1rem}@media
           (max-width:991.98px){footer .btn{padding:.375rem 2rem}}footer
           .content{margin-bottom:5rem}footer
           .content:nth-child(1){border-right:1px solid
           rgba(255,255,255,.33);padding-right:3rem}@media
           (max-width:767.98px){footer .content{text-align:center}footer
           .content:nth-child(1){border-right:none;padding:0 15px}}footer
           .content:nth-child(2){border-right:1px

[ ERROR ]  Runtime error detected during componentWillLoad(): stencil-router
           Cannot read property '_history' of null TypeError: Cannot read
           property '_history' of null at Window.get history [as history]
           (/Users/billy/OPENFORGE.IO/node_modules/jsdom/lib/jsdom/browser/Window.js:178:79)
           at Object.browser (evalmachine.<anonymous>:2:194176) at
           t.componentWillLoad (evalmachine.<anonymous>:2:200438) at update
           (/Users/billy/OPENFORGE.IO/node_modules/@stencil/core/dist/server/index.js:1858:48)
           at plt.queue.tick
           (/Users/billy/OPENFORGE.IO/node_modules/@stencil/core/dist/server/index.js:1816:34)
           at flush
           (/Users/billy/OPENFORGE.IO/node_modules/@stencil/core/dist/server/index.js:3244:33)
           at _combinedTickCallback (internal/process/next_tick.js:131:7) at
           process._tickCallback (internal/process/next_tick.js:180:9)

[ ERROR ]  Runtime error detected during componentDidLoad(): open-forge-app
           t.listen is not a function TypeError: t.listen is not a function at
           t.componentDidLoad (evalmachine.<anonymous>:2:11487) at
           initComponentLoaded
           (/Users/billy/OPENFORGE.IO/node_modules/@stencil/core/dist/server/index.js:1615:55)
           at HTMLUnknownElement.HostElementConstructor.s-init
           (/Users/billy/OPENFORGE.IO/node_modules/@stencil/core/dist/server/index.js:2955:9)
           at propagateComponentLoaded
           (/Users/billy/OPENFORGE.IO/node_modules/@stencil/core/dist/server/index.js:1670:79)
           at initComponentLoaded
           (/Users/billy/OPENFORGE.IO/node_modules/@stencil/core/dist/server/index.js:1628:9)
           at HTMLUnknownElement.HostElementConstructor.s-init
           (/Users/billy/OPENFORGE.IO/node_modules/@stencil/core/dist/server/index.js:2955:9)
           at propagateComponentLoaded
           (/Users/billy/OPENFORGE.IO/node_modules/@stencil/core/dist/server/index.js:1670:79)
           at initComponentLoaded
           (/Users/billy/OPENFORGE.IO/node_modules/@stencil/core/dist/server/index.js:1628:9)
           at HTMLUnknownElement.HostElementConstructor.s-init
           (/Users/billy/OPENFORGE.IO/node_modules/@stencil/core/dist/server/index.js:2955:9)
           at renderUpdate
           (/Users/billy/OPENFORGE.IO/node_modules/@stencil/core/dist/server/index.js:1901:26)

[ ERROR ]  runtime console.error: /
           Error: Could not parse CSS stylesheet at exports.evaluateStylesheet
           (/Users/billy/OPENFORGE.IO/node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:18:21)
           at HTMLStyleElementImpl._attach
           (/Users/billy/OPENFORGE.IO/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:23:5)
           at HTMLHeadElementImpl.insertBefore
           (/Users/billy/OPENFORGE.IO/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:230:22)
           at HTMLHeadElement.insertBefore
           (/Users/billy/OPENFORGE.IO/node_modules/jsdom/lib/jsdom/living/generated/Node.js:182:45)
           at insertStyles
           (/Users/billy/OPENFORGE.IO/node_modules/@stencil/core/dist/server/index.js:4963:18)
           at inlineComponentStyles
           (/Users/billy/OPENFORGE.IO/node_modules/@stencil/core/dist/server/index.js:4956:5)
           at
           /Users/billy/OPENFORGE.IO/node_modules/@stencil/core/dist/server/index.js:5443:17
           at Generator.next (<anonymous>) at
           /Users/billy/OPENFORGE.IO/node_modules/@stencil/core/dist/server/index.js:5419:71
           at new Promise (<anonymous>), /*! * Bootstrap v4.1.0
           (https://getbootstrap.com/) * Copyright 2011-2018 The Bootstrap
           Authors * Copyright 2011-2018 Twitter, Inc. * Licensed under MIT
           (https://github.com/twbs/bootstrap/blob/master/LICENSE)
           */:root{--blue:#638593;--indigo:#323c47;--purple:#6f42c1;--pink:#e83e8c;--red:#dc3545;--orange:#e88212;--yellow:#d8aa0c;--green:#28a745;--teal:#20c997;--cyan:#17a2b8;--white:#fff;--gray:#6d6e71;--gray-dark:#282828;--primary:#e88212;--secondary:#6d6e71;--success:#28a745;--info:#638593;--warning:#d8aa0c;--danger:#dc3545;--light:#f4f5f9;--dark:#282828;--breakpoint-xs:0;--breakpoint-sm:576px;--breakpoint-md:768px;--breakpoint-lg:992px;--breakpoint-xl:1400px;--font-family-sans-serif:("Muli",
           sans-serif),Arial,sans-serif;--font-family-monospace:SFMono-Regular,Menlo,Monaco,Consolas,"Liberation
           Mono","Courier
           New",monospace}*,::after,::before{-webkit-box-sizing:border-box;box-sizing:border-box}html{font-family:sans-serif;line-height:1.15;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%;-ms-overflow-style:scrollbar;-webkit-tap-highlight-color:rgba(23,23,25,0)}@-ms-viewport{width:device-width}article,aside,dialog,figcaption,figure,footer,header,hgroup,main,nav,section{display:block}body{margin:0;font-family:Muli,sans-serif,Arial,sans-serif;font-size:1rem;font-weight:400;line-height:2;color:#212529;text-align:left;background-color:#fff}[tabindex="-1"]:focus{outline:0!important}hr{-webkit-box-sizing:content-box;box-sizing:content-box;height:0;overflow:visible}h1,h2,h3,h4,h5,h6{margin-top:0}abbr[data-original-title],abbr[title]{text-decoration:underline;-webkit-text-decoration:underline
           dotted;text-decoration:underline
           dotted;cursor:help;border-bottom:0}address{margin-bottom:1rem;font-style:normal;line-height:inherit}dl,ol,ul{margin-top:0;margin-bottom:1rem}ol

`

**Comment by PaulPaulDevelops** [comment]
It appears that #116 somehow removed @stencil/sass as a dependency from the project. I directly injected back into the project and [committed](https://github.com/openforge/OPENFORGE.IO/commit/2bfa8333c5069d83c58f2d95fa3c8a7ad532da6c) to `develop`. Please re-test and see that the error has been resolved.

**Comment by Wholloran** [comment]
No longer seeing the error, Closing the ticket

**Comment by Wholloran** [comment]
Re-opening the issue, errors are still genreating when running the app 
" Runtime error detected while rendering: stencil-route
           ENOENT: no such file or directory, open
           '/Users/billy/OPENFORGE.IO/www/build/app/app-hero-home.es5.js' Error:
           ENOENT: no such file or directory, open
           '/Users/billy/OPENFORGE.IO/www/build/app/app-hero-home.es5.js' at
           Object.fs.openSync (fs.js:646:18) at Object.fs.readFileSync
           (fs.js:551:33) at NodeFs.readFileSync
           (/Users/billy/OPENFORGE.IO/node_modules/@stencil/core/dist/sys/node/index.js:684:19)
           at InMemoryFileSystem.readFileSync
           (/Users/billy/OPENFORGE.IO/node_modules/@stencil/core/dist/server/index.js:646:39)
           at loadFile
           (/Users/billy/OPENFORGE.IO/node_modules/@stencil/core/dist/server/index.js:3676:39)
           at Object.requestBundle
           (/Users/billy/OPENFORGE.IO/node_modules/@stencil/core/dist/server/index.js:3670:17)
           at Object.domApi.$createElement
           (/Users/billy/OPENFORGE.IO/node_modules/@stencil/core/dist/server/index.js:3438:17)
           at createElm
           (/Users/billy/OPENFORGE.IO/node_modules/@stencil/core/dist/server/index.js:2331:24)
           at addVnodes
           (/Users/billy/OPENFORGE.IO/node_modules/@stencil/core/dist/server/index.js:2428:21)
           at patchVNode
           (/Users/billy/OPENFORGE.IO/node_modules/@stencil/core/dist/server/index.js:2608:17)

[ ERROR ]  runtime console.error: /
           caught error , TypeError: Cannot read property 'querySelector' of
           undefined

[ ERROR ]  runtime console.error: /
           caught error componentDidLoad open-forge-app, TypeError: Cannot read
           property 'querySelector' of undefined

[ ERROR ]  runtime console.error: /
           Error: Could not parse CSS stylesheet at exports.evaluateStylesheet
           (/Users/billy/OPENFORGE.IO/node_modules/jsdom/lib/jsdom/living/helpers/stylesheets.js:18:21)
           at HTMLStyleElementImpl._attach
           (/Users/billy/OPENFORGE.IO/node_modules/jsdom/lib/jsdom/living/nodes/HTMLStyleElement-impl.js:23:5)
           at HTMLHeadElementImpl.insertBefore
           (/Users/billy/OPENFORGE.IO/node_modules/jsdom/lib/jsdom/living/nodes/Node-impl.js:230:22)
           at HTMLHeadElement.insertBefore
           (/Users/billy/OPENFORGE.IO/node_modules/jsdom/lib/jsdom/living/generated/Node.js:182:45)
           at insertStyles
           (/Users/billy/OPENFORGE.IO/node_modules/@stencil/core/dist/server/index.js:4963:18)
           at inlineComponentStyles
           (/Users/billy/OPENFORGE.IO/node_modules/@stencil/core/dist/server/index.js:4956:5)
           at
           /Users/billy/OPENFORGE.IO/node_modules/@stencil/core/dist/server/index.js:5443:17
           at Generator.next (<anonymous>) at
           /Users/billy/OPENFORGE.IO/node_modules/@stencil/core/dist/server/index.js:5419:71
           at new Promise (<anonymous>),
           footer{background:#282828;color:#fff;padding:5rem 0 2rem}footer
           h2{color:#e88212;font-size:1.6rem;margin-bottom:2rem}footer a,footer
           p{color:#fff;display:block;font-size:.8em;margin-bottom:1rem}@media
           (max-width:991.98px){footer .btn{padding:.375rem 2rem}}footer
           .content{margin-bottom:5rem}footer
           .content:nth-child(1){border-right:1px solid
           rgba(255,255,255,.33);padding-right:3rem}@media
           (max-width:767.98px){footer .content{text-align:center}footer
           .content:nth-child(1){border-right:none;padding:0 15px}}footer
           .content:nth-child(2){border-right:1px"
